version: '3'
services:  
  backend:
    build:
      context: ./backend # Path to the directory containing the Python app
      dockerfile: Dockerfile  # Specify the Python Dockerfile
    environment:
      - DEMO=true
      - mongo_ip=${mongo_ip}
      - mongo_port=${mongo_port}
      - AIServerPort=${AIServerPort}
      - AIServicesIp=${AIServicesIp}
    ports:
      - "5001:5001"  # Map the container's port 5001 to the host's port 5001
    volumes:
      - ./backend:/app  # Mount the current directory into the /app directory in the container
      - /home/ubuntu/ai-tutor-bucket/data:/data
      - /home/ubuntu/ai-tutor-bucket/application/archive:/archive
      - /home/ubuntu/ai-tutor-bucket/application/backend/config:/config
      - /home/ubuntu/ai-tutor-bucket/application/backend/logs:/logs/backend

