version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "5001:5001"
      - "5002:5000"
    depends_on:
      - mongodb
    environment:
      DEMO: "false"
      IP_ADDRESS: "0.0.0.0"
      MONGO_IP_ADDRESS: "mongodb"
      AIServicesIp: "localhost"
      AIServerPort: "4001"
    networks:
      - genx-platform-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - genx-platform-network

networks:
  genx-platform-network:
    name: genx-platform-network
    driver: bridge

volumes:
  mongodb-data:
