version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G
    environment:
      - DEMO=false
      - IP_ADDRESS=host.docker.internal
      - MONGO_IP_ADDRESS=host.docker.internal
      - AIServicesIp=host.docker.internal
      - AIServerPort=4001
    ports:
      - "5002:5000"
      - "5001:5001"
    networks:
      - genx-network

  # You can uncomment this if you want to run MongoDB locally in the dev container
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb-data:/data/db
  #   networks:
  #     - genx-network

networks:
  genx-network:
    driver: bridge

# volumes:
#   mongodb-data:
